export const CATEGORY_ICONS: Record<string, string> = {
  fruits: '🍎',
  fruit: '🍎',
  vegetables: '🥦',
  vegetable: '🥦',
  veggies: '🥦',
  dairy: '🥛',
  milk: '🥛',
  bakery: '🍞',
  bread: '🍞',
  meat: '🥩',
  poultry: '🍗',
  chicken: '🍗',
  seafood: '🐟',
  fish: '🐟',
  drinks: '🧃',
  beverages: '🧃',
  beverage: '🧃',
  snacks: '🍿',
  frozen: '🧊',
  breakfast: '🥞',
  cereals: '🥣',
  cereal: '🥣',
  personal: '🧴',
  hygiene: '🧴',
  cleaning: '🧹',
  household: '🏠',
  baby: '🍼',
  organic: '🌿',
  spices: '🌶️',
  condiments: '🫙',
  oils: '🫒',
  sweets: '🍬',
  chocolates: '🍫',
  chocolate: '🍫',
  eggs: '🥚',
  cheese: '🧀',
  nuts: '🥜',
  rice: '🍚',
  pasta: '🍝',
  noodles: '🍜',
};

export function getCategoryIcon(name: string): string {
  const key = name.toLowerCase().trim();
  return CATEGORY_ICONS[key] ?? '🛒';
}
